Type: AWS::DynamoDB::Table
Properties:
  TableName: ProductTable
  AttributeDefinitions:
    - AttributeName: productId
      AttributeType: S
    - AttributeName: isDeleted
      AttributeType: S
  KeySchema:
    - AttributeName: productId
      KeyType: HASH
  GlobalSecondaryIndexes:
    - IndexName: isDeletedIndex
      KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
      Projection:
        ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ProvisionedThroughput:
    ReadCapacityUnits: 5
    WriteCapacityUnits: 5
